# Generated by Django 5.2 on 2025-05-08 14:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicCoordinatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_lastname', models.CharField(max_length=100)),
                ('second_lastname', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('birthdate', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7)])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'AcademicCoordinator'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_lastname', 'first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_lastname', models.CharField(max_length=100)),
                ('second_lastname', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('birthdate', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7)])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'director'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_lastname', 'first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuardianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_lastname', models.CharField(max_length=100)),
                ('second_lastname', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('birthdate', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7)])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'guardian'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_lastname', 'first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecretaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_lastname', models.CharField(max_length=100)),
                ('second_lastname', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('birthdate', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7)])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'secretary'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_lastname', 'first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_lastname', models.CharField(max_length=100)),
                ('second_lastname', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('birthdate', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7)])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='sgae_app.guardianmodel')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_lastname', 'first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_lastname', models.CharField(max_length=100)),
                ('second_lastname', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('birthdate', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7)])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_lastname', 'first_name'],
                'abstract': False,
            },
        ),
    ]
