# Generated by Django 5.2 on 2025-05-15 18:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del grupo')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('section', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sección')),
                ('shift', models.CharField(blank=True, max_length=10, null=True, verbose_name='Turno')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicCoordinatorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_lastname', models.CharField(max_length=100)),
                ('second_lastname', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('birthdate', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7)])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'AcademicCoordinator'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_lastname', 'first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassRoomModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del aula')),
                ('capacity', models.IntegerField(verbose_name='Capacidad')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DirectorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_lastname', models.CharField(max_length=100)),
                ('second_lastname', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('birthdate', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7)])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'director'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_lastname', 'first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnrollmentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField(verbose_name='Año académico')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de matrícula')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('withdrawn', 'Retirada'), ('graduated', 'Graduado')], default='active', max_length=20, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='sgae_app.groupmodel')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='GuardianModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_lastname', models.CharField(max_length=100)),
                ('second_lastname', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('birthdate', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7)])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'guardian'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_lastname', 'first_name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='sgae_app.schedulemodel', verbose_name='Horario'),
        ),
        migrations.CreateModel(
            name='SecretaryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_lastname', models.CharField(max_length=100)),
                ('second_lastname', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('birthdate', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7)])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'secretary'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_lastname', 'first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_lastname', models.CharField(max_length=100)),
                ('second_lastname', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('birthdate', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7)])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('enrollment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='sgae_app.enrollmentmodel')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='sgae_app.guardianmodel')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_lastname', 'first_name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='enrollmentmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='sgae_app.studentmodel'),
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_lastname', models.CharField(max_length=100)),
                ('second_lastname', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('birthdate', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7)])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_lastname', 'first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectAssignmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField(verbose_name='Año académico')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_assignments', to='sgae_app.classroommodel')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='sgae_app.groupmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='sgae_app.subjectmodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='sgae_app.teachermodel')),
            ],
            options={
                'verbose_name': 'Asignación de materia',
                'verbose_name_plural': 'Asignaciones de materias',
                'unique_together': {('teacher', 'subject', 'group', 'academic_year')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='groupmodel',
            unique_together={('name', 'year', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentmodel',
            unique_together={('student', 'academic_year')},
        ),
        migrations.CreateModel(
            name='ScheduleItemModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=9)),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sgae_app.schedulemodel')),
                ('subject_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='sgae_app.subjectassignmentmodel')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('subject_assignment', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='GradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subperiod', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subperíodo')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota')),
                ('evaluation_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de evaluación')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='sgae_app.studentmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='sgae_app.subjectmodel')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grades', to='sgae_app.teachermodel')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-registered_at'],
                'unique_together': {('student', 'subject', 'subperiod', 'evaluation_type')},
            },
        ),
    ]
