# Generated by Django 5.2 on 2025-05-26 03:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgae_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmodel',
            options={'ordering': ['year', 'name', 'section'], 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='name',
            field=models.CharField(help_text='Nombre corto del grupo (ej: 1A, 2B)', max_length=10, verbose_name='Nombre del grupo'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Horario asociado al grupo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='sgae_app.schedulemodel', verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='section',
            field=models.CharField(blank=True, help_text='Sección del grupo (opcional)', max_length=10, null=True, verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='shift',
            field=models.CharField(blank=True, choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde')], help_text='Turno en el que se imparte el grupo', max_length=10, null=True, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='year',
            field=models.PositiveIntegerField(help_text='Año académico (ej: 2025)', validators=[django.core.validators.MinValueValidator(2000, 'El año debe ser mayor o igual a 2000'), django.core.validators.MaxValueValidator(2100, 'El año no puede ser mayor a 2100')], verbose_name='Año académico'),
        ),
        migrations.AddIndex(
            model_name='groupmodel',
            index=models.Index(fields=['year', 'name'], name='sgae_app_gr_year_d8bb54_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmodel',
            index=models.Index(fields=['shift'], name='sgae_app_gr_shift_ec0a7a_idx'),
        ),
    ]
