# Generated by Django 5.2 on 2025-05-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgae_app', '0002_alter_groupmodel_options_alter_groupmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='shift',
            field=models.CharField(blank=True, choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde')], help_text='Turno en el que se imparte el grupo (Mañana o Tarde)', max_length=20, null=True, verbose_name='Turno'),
        ),
    ]
